// <auto-generated />
using System;
using LoyaltyAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoyaltyAPI.Migrations
{
    [DbContext(typeof(LoyaltyDbContext))]
    partial class LoyaltyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LoyaltyAPI.Models.Activity", b =>
                {
                    b.Property<int>("activity_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("activity_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("date_from")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("date_time")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("date_to")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("points")
                        .HasColumnType("int");

                    b.Property<int>("system_source_id")
                        .HasColumnType("int");

                    b.HasKey("activity_id");

                    b.HasIndex("system_source_id");

                    b.ToTable("activity", (string)null);
                });

            modelBuilder.Entity("LoyaltyAPI.Models.ClientWallet", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<int>("BR_ID")
                        .HasColumnType("int");

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<string>("ContactNo")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("REF_NO")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tblclientwallet", (string)null);
                });

            modelBuilder.Entity("LoyaltyAPI.Models.LoyaltyData", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClientID"));

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tier");

                    b.HasKey("ClientID");

                    b.ToTable("loyalty_data", (string)null);
                });

            modelBuilder.Entity("LoyaltyAPI.Models.Referral", b =>
                {
                    b.Property<int>("ReferralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReferralId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<string>("ReferralCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("referral_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("ReferralId");

                    b.HasIndex("ReferralCode")
                        .IsUnique();

                    b.ToTable("referral", (string)null);
                });

            modelBuilder.Entity("LoyaltyAPI.Models.SystemSource", b =>
                {
                    b.Property<int>("system_source_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("system_source_id"));

                    b.Property<string>("fetch_method")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("system_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("system_source_id");

                    b.ToTable("system_source", (string)null);
                });

            modelBuilder.Entity("LoyaltyAPI.Models.Tier", b =>
                {
                    b.Property<int>("tier_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("tier_id"));

                    b.Property<string>("badge")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("date_from")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("date_to")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("points")
                        .HasColumnType("int");

                    b.HasKey("tier_id");

                    b.ToTable("tier", (string)null);
                });

            modelBuilder.Entity("LoyaltyAPI.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int")
                        .HasColumnName("activity_id");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<string>("CobxTransactionId")
                        .HasColumnType("longtext")
                        .HasColumnName("cobx_transaction_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("reference_id");

                    b.Property<int?>("ReferralId")
                        .HasColumnType("int")
                        .HasColumnName("referral_id");

                    b.HasKey("TransactionId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("ReferenceId")
                        .IsUnique();

                    b.HasIndex("ReferralId");

                    b.ToTable("transaction", (string)null);
                });

            modelBuilder.Entity("LoyaltyAPI.Models.Activity", b =>
                {
                    b.HasOne("LoyaltyAPI.Models.SystemSource", "system_source")
                        .WithMany()
                        .HasForeignKey("system_source_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("system_source");
                });

            modelBuilder.Entity("LoyaltyAPI.Models.Transaction", b =>
                {
                    b.HasOne("LoyaltyAPI.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoyaltyAPI.Models.Referral", "Referral")
                        .WithMany()
                        .HasForeignKey("ReferralId");

                    b.Navigation("Activity");

                    b.Navigation("Referral");
                });
#pragma warning restore 612, 618
        }
    }
}
